title: Couture d'Opale
responsable: Patricia BRUVRY
siren: 984726828
siret: 98472682800010
adresse: 14, Rue Jean Ferrat
codepostal: 62720
ville: Rinxent
pays: FRANCE
telephone: 06.98.08.46.78
email: couturedopale@gmail.com
facebook: Couture d'Opale
linkfacebook: https://www.facebook.com/people/Couture-dOpale/61557730299464/
hebergeur: onRender.com